spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://192.168.1.11:5432/postgres
    username: dbuser
    password: secret
    default-auto-commit: false
    driverClassName: org.postgresql.Driver
    hikari:
      schema: dms
      connection-timeout: 90000000
      default-auto-commit: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 7070
  servlet:
    context-path: /api
    session:
      timeout: 220m

app:
 fileStore:
   baseFolder: "/home/palmyra/Desktop/"

palmyra:
  database: 
    schemas: dms
aws:
  s3:
    bucketName: hpcbucket
    region: ap-south-1
    accessKey: AKIAIOSFODNN7EXAMPLE
    secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    endpoint: http://192.168.1.11:9000
