spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    default-auto-commit: false
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ${DB_SCHEMA}
      maximum-pool-size: ${DB_POOL_MAX}
      minimum-idle: ${DB_POOL_IDLE}
      connection-timeout: 2000
      default-auto-commit: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: ${SERVER_PORT}
  jetty:
    threads:
      min: ${JETTY_MIN_THREAD}
      max: ${JETTY_MAX_THREAD}
  servlet:
    context-path: /api
    session:
      timeout: 220m

app:
 fileStore:
   baseFolder: "/home/palmyra/Desktop/"

palmyra:
  database: 
    schemas: ${DB_SCHEMA}
aws:
  s3:
    bucketName: ${S3_BUCKET}
    region: ${S3_REGION}
    accessKey: ${S3_ACCESSKEY}
    secretKey: ${S3_SECRETKEY}
    endpoint: ${S3_ENDPOINT}
    corePoolSize: ${S3_POOL_CORE}
    maximumPoolSize: ${S3_POOL_MAX}
    keepAliveTime: 600
    conAcqTimeout: ${S3_CON_ACQ_TIMEOUT}
    maxConcurrency: ${S3_CLIENT_CONCURRENCY}
    clientBuffer: ${S3_CLIENT_BUFFER_KB}
