
app:
 upload:
   url: "http://localhost:8080/api/"
   username: "admin@gmail.com"
   password: "ad"
   policyFolder: "D:\\hlc\\policy_dataload\\neft"
   masterCsv: "D:\\hlc\\policy_dataload\\neft\\adv_reference_number.csv"
   parallel: 1
   start: 10
   end: 110
